### ISSUE TITLE
Please add Speaker and Lights as IR Devices

### ISSUE THREAD

**Issue by Supergamerx3000** [KiraPC/ha-switchbot-remote#1]
I have successfully connect the Switch Bot Hub 2 with this integration my tv can now control by home assistant. I have also a Soundbar I have add the soundbar as IR Device in SwitchBot but it not show up in Homeassistant. Also my IR Light.

**Comment by KiraPC** [comment]
Hello supergamer.

I don't have soundbar or ir light to test but I'll try to add those devices asap. 

I'm out of home these weekend so maybe I can work on it next.

**Comment by KiraPC** [comment]
@Supergamerx3000 In the 0.2.0-beta.1 version I've added the light entity. Could you please check if on/off feature work?

**Comment by KiraPC** [comment]
@Supergamerx3000 did you tested the beta version?

**Comment by Supergamerx3000** [comment]
@KiraPC the switchbot device is shown, when i want to add it to home assistant then this happens:

![grafik](https://github.com/KiraPC/ha-switchbot-remote/assets/61492037/4c688531-736e-4d65-a55d-78065b31daf0)

![grafik](https://github.com/KiraPC/ha-switchbot-remote/assets/61492037/77431ca7-f564-469e-b17b-7bb670f13097)

home assistant does not seem to recognize the device as a light

i can send you the switchbot tokens Then you can try it on yourself

**Comment by KiraPC** [comment]
Mmm @Supergamerx3000 can you show the devices list? This is the customization page, and no customization options are available for light. You should see it as entity.

**Comment by Supergamerx3000** [comment]
nope no device. i can remember when i setup my tv i also click on configure then home assistant ask me in which room i want to add the device

![grafik](https://github.com/KiraPC/ha-switchbot-remote/assets/61492037/865ad138-b964-49a2-ad2f-8b5ebbc1a3a8)

![grafik](https://github.com/KiraPC/ha-switchbot-remote/assets/61492037/5270cc47-74ca-4904-aa18-206b11a94883)
(this is a fresh home assistant instance), I'll test it on another instance

**Comment by Supergamerx3000** [comment]
Switchbot TV IR:
![grafik](https://github.com/KiraPC/ha-switchbot-remote/assets/61492037/c3ea5ebc-d8fa-426e-931d-d203e6adb

vs Light:
![grafik](https://github.com/KiraPC/ha-switchbot-remote/assets/61492037/5e2df53a-f776-48d2-8b8c-7f6dc09f5e70)

**Comment by KiraPC** [comment]
Ok. With this hub do you have also other devices or just the light? Can you please give me more context? In case are you available to provide the switchbot api get devices response?

**Comment by Supergamerx3000** [comment]
These are two different switchbot accounts.

both have a Switch Bot Hub 2. One Switch Bot Hub 2 has a trained TV, which works without any problems even with the new media settings. Otherwise there are no more devices.

The second Switchbot account also only has one SwitchBot Hub 2, where a lamp is trained. This is only shown under Configure but not shown as a light entity.

**Comment by KiraPC** [comment]
That's strange. I need time to mock the API and check.

**Comment by KiraPC** [comment]
@Supergamerx3000 are you able to execute the GET https://api.switch-bot.com/v1.1/devices and post here the response?

I need the exact way the remoteType is wrote

**Comment by Supergamerx3000** [comment]
which program can use for this?

can you please build me a complete request where i only have to insert the token and the secret?

**Comment by KiraPC** [comment]
@Supergamerx3000 nevermind. I was able to add a light to my hub. Now i'm looking for a solution.

**Comment by KiraPC** [comment]
@Supergamerx3000 sorry for pinging you but I can't test

**Comment by Supergamerx3000** [comment]
@KiraPC is have updated but the light not showing as light.

Can i send you the Switch bot API token via Discord?

**Comment by KiraPC** [comment]
@Supergamerx3000 I don't know. How the entity is shown? Can you post a screen? 

The switchbot token is a very personal data

**Comment by Supergamerx3000** [comment]
https://www.youtube.com/watch?v=JTv6DfmxOnQ

Here you see the add process in Home Assistant.

**Comment by KiraPC** [comment]
@Supergamerx3000 ok so it is not shown at all. Yes maybe it is how the remote is described on switchbot. I do need the API response to check better. Do you know postman?

Ps are you sure you're running the latest beta version?

**Comment by Supergamerx3000** [comment]
yes home assistant ask me to update.

i have see postman but not use it, when you send me a screenshot what i must do in postman i can do this.

**Comment by KiraPC** [comment]
I was looking for postman but if you are not confident, maybe it is better to try this library https://pypi.org/project/python-switchbot/

Are you able to use python?

**Comment by Supergamerx3000** [comment]
postman is ready and open :D

above is get because I have to enter GET https://api.switch-bot.com/v1.1/devices.

The only thing I haven't managed to authorize yet. where do I have to enter the switchbot keys so that postman authenticates himself?

**Comment by Supergamerx3000** [comment]
![grafik](https://github.com/KiraPC/ha-switchbot-remote/assets/61492037/814035a2-5b99-4c5d-92d4-666c17938f02)

**Comment by KiraPC** [comment]
You need to follow this: https://github.com/OpenWonderLabs/SwitchBotAPI#open-token-and-secret-key

then put the values like 
<img width="440" alt="Screenshot 2023-07-26 alle 20 09 02" src="https://github.com/KiraPC/ha-switchbot-remote/assets/46629148/c51efd8e-c348-4fc3-bcf2-cdae78f8ef11">

**Comment by Supergamerx3000** [comment]
here are the output:

{
    "statusCode": 100,
    "body": {
        "deviceList": [
            {
                "deviceId": "C7873AEC302C",
                "deviceName": "Hub-Thomas",
                "deviceType": "Hub 2",
                "enableCloudService": true,
                "hubDeviceId": ""
            }
        ],
        "infraredRemoteList": [
            {
                "deviceId": "01-202307152142-05570990",
                "deviceName": "Licht-Weiß",
                "remoteType": "DIY Light",
                "hubDeviceId": "C7873AEC302C"
            }
        ]
    },
    "message": "success"

**Comment by Supergamerx3000** [comment]
{
    "statusCode": 100,
    "body": {
        "deviceList": [
            {
                "deviceId": "C7873AEC302C",
                "deviceName": "Hub-Thomas",
                "deviceType": "Hub 2",
                "enableCloudService": true,
                "hubDeviceId": ""
            }
        ],
        "infraredRemoteList": [
            {
                "deviceId": "01-202307152142-05570990",
                "deviceName": "Licht-Weiß",
                "remoteType": "DIY Light",
                "hubDeviceId": "C7873AEC302C"
            }
        ]
    },
    "message": "success"
}

**Comment by Supergamerx3000** [comment]
`{
    "statusCode": 100,
    "body": {
        "deviceList": [
            {
                "deviceId": "C7873AEC302C",
                "deviceName": "Hub-Thomas",
                "deviceType": "Hub 2",
                "enableCloudService": true,
                "hubDeviceId": ""
            }
        ],
        "infraredRemoteList": [
            {
                "deviceId": "01-202307152142-05570990",
                "deviceName": "Licht-Weiß",
                "remoteType": "DIY Light",
                "hubDeviceId": "C7873AEC302C"
            }
        ]
    },
    "message": "success"
}`

**Comment by Supergamerx3000** [comment]
![grafik](https://github.com/KiraPC/ha-switchbot-remote/assets/61492037/2cd11362-a02e-44c7-8324-309be83a3909)

**Comment by KiraPC** [comment]
@Supergamerx3000 Perfect. I handled this remoteType, please install the beta3.

I've also included a basic support for speaker.

**Comment by Supergamerx3000** [comment]
@KiraPC thank you very much. The Light is working, the request is still running a bit slow, about 5–7 seconds. But that's okay.

**Comment by Supergamerx3000** [comment]
@KiraPC thank you very much. The Light is working, the request is still running a bit slow, about 5–7 seconds. But that's okay.

**Comment by KiraPC** [comment]
@Supergamerx3000 great. I'll thinking on how to increase performance but the switchbot api needs authorization fresh so i need to encrypt the token every times. 

Anyway, have you tested the speaker?
