### ISSUE TITLE
Seeing the Air con but not adding it.

### ISSUE THREAD

**Issue by itnassol** [KiraPC/ha-switchbot-remote#11]
Hi there, I have added this excellent integration, and followed the instructions, however when I click configure, it seems to see the remote on the hub.

![Settings_–_Home_Assistant_-_2023-09-11_07 34 05](https://github.com/KiraPC/ha-switchbot-remote/assets/26282121/5fe13499-b212-40f0-b014-a6ac9e6dbcf5)

I click Submit and get this..

![Settings_–_Home_Assistant_-_2023-09-11_07 34 36](https://github.com/KiraPC/ha-switchbot-remote/assets/26282121/3cc38aa5-253c-4fd5-9986-486791d7aa87)

Then submit again and get this...

![Settings_–_Home_Assistant_-_2023-09-11_07 34 53](https://github.com/KiraPC/ha-switchbot-remote/assets/26282121/c2464e43-35d8-4a31-ab7f-21e682386331)

After that nothing happens, any ideas, I have so far, reloaded, rebooted, re-installed.

Thanks.

Andrew

**Comment by KiraPC** [comment]
Hello @itnassol 

I'll give you the correct support next week!

**Comment by KiraPC** [comment]
@itnassol could you please check with the new beta if you can add your device?

**Comment by itnassol** [comment]
> @itnassol could you please check with the new beta if you can add your device?

Hi there, moving to the latest beta, seems to have sorted the problem, I will test over a couple of days and let you know how it goes. Thanks you so much.

**Comment by KiraPC** [comment]
Please close the issue if it is solved.

**Comment by itnassol** [comment]
Hi there, Sorry for the delay, My wife was ill,.,, better now so did some serious testing. There is only one small glitch that I can find, My Aircon uses the same command for on and off, so if I turn it on using the remote then your system shows the temp and mode beautifully, I can then choose off and it turns off quickly, however I then can't turn it back on again from the integrations, I really need an on and off like in the switch Bot AC screen, any ideas?

**Comment by joshepw** [comment]
You can create a "Another" control type in Switchbot App and  configure in the integration as On/Off command

**Comment by itnassol** [comment]
HI there, excellent idea, have set that up with one button for On/Off, showed up straight away, the problem now is it is off by default, I turn it on and it does turn on the AC unit but the button on the device in HA jumps back to off. There are no sensors I can add that are directly from the AC unit, however I have it plugged in to a Z-Wave socket that tells me if it's running, so when the unit is off the plug shows 0.2w when its on, it is way over this.

I thought maybe it was this sensor never showing 0, so I built a template for that sensor where it shows 0 when at 0.2 and 10 when above that, but it's still dropping to off every time I click it.

Any ideas? Cheers.

**Comment by itnassol** [comment]
Yeah no worries, it's this one..
[https://www.amazon.co.uk/gp/product/B084ZLV8TG/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&th=1](url)
Cheers

**Comment by KiraPC** [comment]
@itnassol Have you configured the power sensor with your socket homeassistant entity_id?

**Comment by joshepw** [comment]
@itnassol can you test with the new beta version? (`1.0.1-beta.0`) 

Go to configuration and disable the "Override the native 'off' command" and save it

**Comment by itnassol** [comment]
Yes I did add the power sensor, I have now upgraded to the new beta, where do I find the "Override the native 'off'  it is not under the config? 
![Settings_–_Home_Assistant_-_2023-10-11_08 15 20](https://github.com/KiraPC/ha-switchbot-remote/assets/26282121/de8a1afc-3bc5-40b3-be69-f02732e02a3a)

**Comment by KiraPC** [comment]
@itnassol mmm the sensor id should has the pattern "sensor.xxx"

![Screenshot 2023-10-11 alle 09 19 40](https://github.com/KiraPC/ha-switchbot-remote/assets/46629148/60cdb13d-6c63-49b6-99ab-3ea010681c66)

**Comment by itnassol** [comment]
The entity does.. that's just friendly name...
![image](https://github.com/KiraPC/ha-switchbot-remote/assets/26282121/9677e0de-6058-440f-9cce-8219bbfc90b7)

**Comment by KiraPC** [comment]
@itnassol  Ok sorry, so this isn't working? Do you see the sensor value change when you turn on the socket?

**Comment by itnassol** [comment]
No worries, I am very, very thankful for your help on this one. 

Yes, I have it plugged in to a Z-Wave socket that tells me if it's running, so when the unit is off the plug shows 0.2w when its on, it is way over this.

I thought maybe it was this sensor never showing 0, so I built a template for that sensor where it shows 0 when at 0.2 and 10 when above that, but it's still dropping to off every time I click it.

**Comment by KiraPC** [comment]
@itnassol here the problem. You have to configure a power sensor that indicate just On/Off state.

**Comment by itnassol** [comment]
Ok I have one of those already, I will try that.

**Comment by itnassol** [comment]
Ok, I think a recap might be helpful, this is the basic problem, when I click the button it does fire up the AC, but it goes straight back off again, however, the AC stays on, if I click again the AC will turn off, so it is sending the correct signal.

https://github.com/KiraPC/ha-switchbot-remote/assets/26282121/21e5ce4e-9788-4ef6-adaf-e079d30ff395

I built a template to give me just on or off as below.

`  - name: "ACOff"
    unique_id: 23021010
    state: >-
        {% if is_state('sensor.ab_ac_rb_electric_consumption_w_2', '0.2') %}
        Off
        {% else %}
        On
        {% endif %}`

This works as it show off or on correctly for the AC, as a work around I have added a button helper to the dashboard that just turns the button on each time, but f possible would be nice to have the toggle that shows the state.

**Comment by KiraPC** [comment]
@itnassol so, is it working now? How your appliance is mapped by this integration?

**Comment by itnassol** [comment]
Turning the toggle on, does turn on the AC, however as you can see from the video, it turns off, if I then turn it on again it turn the AC off then turns off again. It's like the turning on of the toggle is sending the correct signal, but then flicks back to off.

**Comment by KiraPC** [comment]
@itnassol can you show the appliance entity type?

**Comment by itnassol** [comment]
In Switch bot is is in as "other" is that what you meant?

**Comment by KiraPC** [comment]
@itnassol no, is it one of the following:

- button
- remote
- climate
- fan 
- light
- media_player
- vacum
- water_heater

I suppose is missing the implementation to get the device status

**Comment by itnassol** [comment]
I was using the Air Conditioner remote on Switchbot but joshepw advised to move to "other remote" 

![Screenshot_20231013-101914_SwitchBot](https://github.com/KiraPC/ha-switchbot-remote/assets/26282121/335e6034-865a-49c8-9d28-28b0871a7cae)
![Screenshot_20231013-101923_SwitchBot](https://github.com/KiraPC/ha-switchbot-remote/assets/26282121/918a869d-d71e-44b0-a5a9-e284b9ce20bc)

Yes the ACOff is a power sensor.

**Comment by KiraPC** [comment]
Have you configured it here?

![Screenshot 2023-10-13 alle 11 37 47](https://github.com/KiraPC/ha-switchbot-remote/assets/46629148/b856bbdf-d68c-4042-8a01-33a884ef0848)

**Comment by itnassol** [comment]
Where is that? I've done this...
![Settings_–_Home_Assistant_-_2023-10-13_17 41 11](https://github.com/KiraPC/ha-switchbot-remote/assets/26282121/576ed085-af2e-442f-a5b9-aed9eb4b44fc)

**Comment by KiraPC** [comment]
@itnassol have you figured out?

**Comment by KiraPC** [comment]
> Hi @KiraPC,
> 
> Apologies if this has been answered somewhere. I cant seem to find anything. Im just at the stage where Im trying to add the integration after downloading from HACS. When I add it from the list, it asks for a name for the Hub and the token and secret. On entering the details the window flashes away and the form is shown with all the fields empty. I cant actually get to the stage where it is shown with all of the other integrations. Im fairly new to Home Assistant and may be doing something wrong here.
> 
> 1. Followed instructions on downloading through HACS
> 2. Sourced the token and secret via the app on mobile device
> 3. Tested response using the API URL via power shell with positive response (API v1.0) so secret works
> 4. Use of these when adding the integration returns a suspected error. The same thing happens if I put "a" in all 3 fields, just faster as the failed response is returned faster.
> 
> Just wondering if there are any quirks im missing here. I also rolled back to v1.1.1 incase there was an issue with the latest. Unsure what im doing wrong.

Hello @LIrahara 

Could you please open another issue attaching some screen of the error (or a recording) and the logs from the latest integration version?
