### ISSUE TITLE
Brand Icon

### ISSUE THREAD

**Issue by KiraPC** [KiraPC/ha-switchbot-remote#13]
To make Homeassistant display an icon for a custom integration it need to be in the brands repository: https://github.com/home-assistant/brands/tree/master

I'm not good with graphics thinks or some of this stuff, so let me ask to you to prepare some simple pngs (refer to the ones inside the repo for dimensions). 

I was thinks to something like original switchbot logs greyscaled with a remote or something similar.

Thanks.

**Comment by joshepw** [comment]
<img width="128" alt="icon@" src="https://github.com/KiraPC/ha-switchbot-remote/assets/1638280/1269ba85-58eb-4661-8850-a6fffb660044">
<img width="1900" alt="logo@2x" src="https://github.com/KiraPC/ha-switchbot-remote/assets/1638280/aa863985-6f23-43f1-b07f-aa8092be1bc8">
![logo](https://github.com/KiraPC/ha-switchbot-remote/assets/1638280/a1aa5ce1-f8da-4480-bfa8-edd3e9227d15)
<img width="256" alt="icon@2x" src="https://github.com/KiraPC/ha-switchbot-remote/assets/1638280/fa1a2e49-ca02-4c4c-a8fe-fe01c0d47540">

**Comment by joshepw** [comment]
Icon
<img width="128" alt="icon@" src="https://github.com/KiraPC/ha-switchbot-remote/assets/1638280/ae29d60d-f8da-4d1d-9b45-f75598f3774f">

Icon@2x
<img width="256" alt="icon@2x" src="https://github.com/KiraPC/ha-switchbot-remote/assets/1638280/62d9a5e7-cf8d-43e1-a7a0-25fc2cd68298">

Logo 
<img width="1900" alt="logo" src="https://github.com/KiraPC/ha-switchbot-remote/assets/1638280/066268b5-c4e1-4994-8b67-e5bf198ba706">

Logo@2x
<img width="1900" alt="logo@2x" src="https://github.com/KiraPC/ha-switchbot-remote/assets/1638280/a0483516-da06-4ffa-a1c7-b460df86578c">

**Comment by KiraPC** [comment]
@joshepw Amazing. Thanks you a lot. Would you like to open a PR on the icons repo? Or I'll do by myself tomorrow

**Comment by joshepw** [comment]
Now appears in main repo, thanks!
