### ISSUE TITLE
Add topics to repository and prepare to plublic to defaults HACS repos

### ISSUE THREAD

**Issue by joshepw** [KiraPC/ha-switchbot-remote#19]
@KiraPC Could you help me by adding the `topics` that are attached to the image?

With this we would be almost ready to be able to publish to the official HACS repositories

![Screenshot 2023-10-09 at 9 30 54 AM](https://github.com/KiraPC/ha-switchbot-remote/assets/1638280/d7d54f3d-e852-4c55-903d-47b3605b9b17)

**Comment by KiraPC** [comment]
@joshepw I did not get you, could you explain?

**Comment by joshepw** [comment]
This is teh guide to add topics https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics

**Comment by KiraPC** [comment]
@joshepw done

**Comment by joshepw** [comment]
Thanks

**Comment by joshepw** [comment]
@KiraPC can you follow this guide to publish to official HACS repo? 

https://hacs.xyz/docs/publish/include/#check-repository

Only the owner of the repository can publish, everiting of the validation and actions are ready.

**Comment by KiraPC** [comment]
@joshepw https://github.com/hacs/default/pull/2104
