### ISSUE TITLE
Use channel number for settop box

### ISSUE THREAD

**Issue by Maetzi87** [KiraPC/ha-switchbot-remote#24]
Hi :-)
First, thank you very much for this integration!
I have a problem, assuming I'm just too dump to set it up correctly...
Your description  says  "Channel number to source via service" should be possible for settop boxes.
But if I try to add the numbers to my settop box (which is shown and power on/off works fine), I get the error, that the buttons do not exist. So I added a completly custom remote where I added the number buttons and on/off button. On/off again works fine, but trying to trigger one of the numbers prompts this error: 
![Screenshot_20231014_084050_Home Assistant](https://github.com/KiraPC/ha-switchbot-remote/assets/118321707/3845001b-3495-4e38-b4e0-94ced6221504)
"Error calling service button/press. OtherRemote.command() takes from 2 to 3 positional arguments but 4 were given."
Could you please tell me how to set it all up to send eg. a "23" command via automation to my settop box? Preferably with the "normal" remote, but if it only works with the completly custom remote that's also fine for me.
I do not have much experience with services yet and I just don't  know, where to start...

**Comment by Maetzi87** [comment]
Forgot to mention: I use a switchbot Hub 2, if this matters. 😅

**Comment by KiraPC** [comment]
related to #25

**Comment by KiraPC** [comment]
Closed https://github.com/KiraPC/ha-switchbot-remote/pull/28
