### ISSUE TITLE
Error when executing Custom Button - "takes from 2 to 3 positional arguments but 4 were given"

### ISSUE THREAD

**Issue by MarcStocker** [KiraPC/ha-switchbot-remote#25]
I was able to find and add my custom remote, however it appears only the power toggle works. 
All other custom buttons within the remote return the same error upon invoking them. 

Integration Debug logs:
[homeassistant_switchbotremote_debug_logs.txt](https://github.com/KiraPC/ha-switchbot-remote/files/12910731/homeassistant_switchbotremote_debug_logs.txt)

![image](https://github.com/KiraPC/ha-switchbot-remote/assets/16886667/3561b79b-217f-4b14-bd10-619718b73bdb)

Switchbot Remote, and HA Integration Setup: 
![image](https://github.com/KiraPC/ha-switchbot-remote/assets/16886667/a71a41c7-8feb-448c-9639-bf57f13fae01)
![image](https://github.com/KiraPC/ha-switchbot-remote/assets/16886667/9786c02b-dad4-482a-8d96-927e3979c8dd)

**Comment by KiraPC** [comment]
@joshepw could you check?

**Comment by Maetzi87** [comment]
Any progress on this?

**Comment by KiraPC** [comment]
@Maetzi87 i'll try to figure out in this weekend, but idk if I have time.

**Comment by Maetzi87** [comment]
Thank you 😀

**Comment by joshepw** [comment]
Hello guys, sorry i will check right now this

**Comment by KiraPC** [comment]
@MarcStocker I've bumped a new release 1.1.1 that should fix this issue.
