### ISSUE TITLE
Power status out of sync

### ISSUE THREAD

**Issue by eboline** [KiraPC/ha-switchbot-remote#26]
I feel like this option is already here and I’m just not sure how to configure it correctly.  Hopefully someone can help!

I’ve successfully programmed a TV to my him and integrated it to HA.  I can turn the TV on and off no issue.  The problem I have is that if someone uses the physical remote, the status is out of sync.  I do have the TV plugged into a smart plug that is always on and measures power and have the power meeting selected in the configuration of the integration.

What am I missing?

**Comment by KiraPC** [comment]
Hello @eboline 

You can configure a power sensor that indicate the status of the remote device. 

You just need to create an helper that indicate if it is on (when consumption in you smart plug is over a value) or off otherwise and use this helper as your tv power sensor.

**Comment by eboline** [comment]
Duh!  This is what I get for trying to figure stuff out long after I should have been asleep!

Thanks for the quick response!

**Comment by KiraPC** [comment]
Ahahaha no problem. Can I close the issue?

**Comment by eboline** [comment]
Definitely!  Thanks again!
