### ISSUE TITLE
No this command

### ISSUE THREAD

**Issue by darkner258** [KiraPC/ha-switchbot-remote#29]
Hi there, I'm not sure what I did wrong. I named the buttons exactly as they are in the SB app, but I get the No this command error. Any ideas?
![image](https://github.com/KiraPC/ha-switchbot-remote/assets/106254929/940e1519-6405-42b9-a3c5-72937ad28bf8)

**Comment by KiraPC** [comment]
This is the same issue mentioned in https://github.com/KiraPC/ha-switchbot-remote/issues/27

This errore message is given by the switchbot api, but idk why you're receiving it.

I'll try to release a new version with some other verbose logs and ask you later a report. Please wait for this.

**Comment by darkner258** [comment]
Sure, please let me know when the update is out and I’ll send you the logs.
Thanks!

**Comment by darkner258** [comment]
Hello @KiraPC I have a debug log available, could that be of any help?
I did a fresh config of the integration, but still getting the same error. I'm trying the SOURCE button

**Comment by KiraPC** [comment]
Hi @darkner258 I've release the package 1.1.2. Please install it and make some test with working and not working devices.

Then attach the log.

Please remember to enable debug for switchbotremote integration adding this piece in your configuration.yaml

`
logger:
  default: info
  logs:
    custom_components.switchbotremote: debug
`

**Comment by darkner258** [comment]
Will do on the weekend when I get back home and I’ll get back to you,
thanks!

**Comment by darkner258** [comment]
Hey @KiraPC, so sorry it took so long. Here is the log. I started by sending a few volume down and up commands taht worked followed by the SOURCE command, that did not. The log is attached
[home-assistant_switchbotremote_2024-01-09T11-51-38.232Z.log](https://github.com/KiraPC/ha-switchbot-remote/files/13873315/home-assistant_switchbotremote_2024-01-09T11-51-38.232Z.log)

**Comment by darkner258** [comment]
Hey @KiraPC , so sorry it took so long. Here is the log. I started by sending a few volume down and up commands taht worked followed by the SOURCE command, that did not. The log is attached
[home-assistant_switchbotremote_2024-01-09T11-56-33.212Z.log](https://github.com/KiraPC/ha-switchbot-remote/files/13873349/home-assistant_switchbotremote_2024-01-09T11-56-33.212Z.log)

**Comment by KiraPC** [comment]
Hi, no problem.

As I guessed, from switchbot the SOURCE command do not exists on the device **02-202306031517-21702508**

```
2024-01-09 12:51:24.515 DEBUG (SyncWorker_6) [custom_components.switchbotremote.client.remote] Sending command SOURCE
2024-01-09 12:51:24.516 DEBUG (SyncWorker_6) [custom_components.switchbotremote.client.remote] Command payload {'commandType': 'customize', 'command': 'SOURCE', 'parameter': 'default'}
2024-01-09 12:51:24.517 DEBUG (SyncWorker_6) [custom_components.switchbotremote.client.client] Calling service https://api.switch-bot.com/v1.1/devices/02-202306031517-21702508/commands
2024-01-09 12:51:25.180 DEBUG (SyncWorker_6) [custom_components.switchbotremote.client.client] Received error in response {'status_code': 160, 'body': {}, 'message': 'No this command'}
```

The request is sent correctly by the component. Maybe there is some space or bad char in the name you give to the button on the switchbot app.

**Comment by darkner258** [comment]
Well that lead me to creating a custom button on the remote with a whole
different name, which worked! Thanks for the help and pointing me in the
right direction :)

**Comment by KiraPC** [comment]
Ok, no problem.

Happy to be useful!
