### ISSUE TITLE
Please add support for fan devices

### ISSUE THREAD

**Issue by AHitos** [KiraPC/ha-switchbot-remote#3]
I just discovered this integration and it works great for my tv but I also have an IR fan connected to the hub. 
I know that fan support it is not yet implemented, but I would like to ask you if you please could add it when you have time. 
Thank you very much for your work on this integration.

**Comment by KiraPC** [comment]
Sure. I'll implement also this too

**Comment by KiraPC** [comment]
@AHitos could you please check if with latest beta you can find your fan device?

**Comment by joshepw** [comment]
Released in stable version `1.0.0.`
