### ISSUE TITLE
Deprecated constant TEMP_CELCIUS

### ISSUE THREAD

**Issue by MrXANA91** [KiraPC/ha-switchbot-remote#34]
From Home Assistant logs :
> Logger: homeassistant.const
> Source: helpers/deprecation.py:205
> 
> TEMP_CELSIUS was used from switchbotremote, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/KiraPC/ha-switchbot-remote/issues

**Comment by MrXANA91** [comment]
New PR request : https://github.com/KiraPC/ha-switchbot-remote/pull/37

**Comment by KiraPC** [comment]
Merged
