### ISSUE TITLE
ClimateEntityFeature settings issues

### ISSUE THREAD

**Issue by MrXANA91** [KiraPC/ha-switchbot-remote#35]
From Home Assistant logs :
> Logger: homeassistant.components.climate
> Source: components/climate/__init__.py:361
> integration: Climate (documentation, issues)
> 
> Entity None (<class 'custom_components.switchbotremote.climate.SwitchBotRemoteClimate'>) does not set ClimateEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/KiraPC/ha-switchbot-remote/issues
> Entity None (<class 'custom_components.switchbotremote.climate.SwitchBotRemoteClimate'>) implements HVACMode(s): auto, cool, dry, fan_only, heat, off and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/KiraPC/ha-switchbot-remote/issues

**Comment by MrXANA91** [comment]
New PR : https://github.com/KiraPC/ha-switchbot-remote/pull/38

**Comment by KiraPC** [comment]
Merged
