### ISSUE TITLE
Custom/learned IR buttons not working

### ISSUE THREAD

**Issue by Tomanic-glitch** [KiraPC/ha-switchbot-remote#44]
I do have custom/learned buttons for Sony TV in the Switchbot app and they work there just fine. In the SwitchBot Remote IR integration the basic commands like Tun ON/OFF, Volume Up/Down and Mute work as well, however, none of the learned/custom commands work and the following error message is displayed whenever I press any of the custom buttons: "Failed to call service button/press. An error occurred: No this command". The commands do have exactly the same names as in the Switchbot app. Attaching the config details as well as log excerpt.

![Config buttons](https://github.com/KiraPC/ha-switchbot-remote/assets/61036575/73c11538-6d5f-48cc-8427-b32eb5a94037)
![Controls](https://github.com/KiraPC/ha-switchbot-remote/assets/61036575/83ee90ef-6787-489c-a72f-2b921a1e80f2)
![Error message](https://github.com/KiraPC/ha-switchbot-remote/assets/61036575/a90570df-d278-4825-a1b4-6716bcd7953c)
![Switchbot App](https://github.com/KiraPC/ha-switchbot-remote/assets/61036575/431ee533-7b0e-4c5b-bec5-073de00b1d66)
![Log](https://github.com/KiraPC/ha-switchbot-remote/assets/61036575/b37552a1-08b0-4c75-9810-2f0a16b8a55e)

**Comment by KiraPC** [comment]
Can you please attach debug logs?

Have you named the button both in app and in the integration exactly in same way, respecting the case?

**Comment by Tomanic-glitch** [comment]
The debug log is attached. Yes the names are exactly the same in both the app and the integration.

[home-assistant_switchbotremote_2024-03-22T22-22-58.156Z.log](https://github.com/KiraPC/ha-switchbot-remote/files/14729008/home-assistant_switchbotremote_2024-03-22T22-22-58.156Z.log)

**Comment by KiraPC** [comment]
@Tomanic-glitch 

So this is the payload sent by the integration to Swithbot API

```
2024-03-22 23:22:51.675 DEBUG (SyncWorker_3) [custom_components.switchbotremote.client.remote] Command payload {'commandType': 'customize', 'command': 'STOP', 'parameter': 'default'}
```

Is your command named STOP on the switchbot App?

**Comment by Tomanic-glitch** [comment]
@KiraPC - Yes that's right the name of the command in Switchbot app is  STOP

![STOP](https://github.com/KiraPC/ha-switchbot-remote/assets/61036575/0b72b73a-91c5-414a-8d7f-536d45f1a3d0)

**Comment by KiraPC** [comment]
Ok, so, I'm sorry but I can't help you more. The API returns that does not exist a command with that name. 

You should try to change the case, do different tests, but this is not an integration related issue.
