### ISSUE TITLE
How to delete devices?

### ISSUE THREAD

**Issue by benswinburne** [KiraPC/ha-switchbot-remote#50]
I've deleted a device from my hub in Switchbot but am unable to delete the device in HA through the integration.

When I click configure, the device is not in the list.

When I go to devices filtered by those from this integration the devices are still present even after restarting HA.

How can I delete devices?

**Comment by KiraPC** [comment]
Fixed in 1.2.2.

Please check and close the issue if works

**Comment by benswinburne** [comment]
Hi,

Thanks for the quick response/fix!

That did indeed remove the device.

Thanks again
