### ISSUE TITLE
Add option to customize Air Conditioner setting

### ISSUE THREAD

**Issue by KiraPC** [KiraPC/ha-switchbot-remote#6]
Ability to set some air conditioner values:

- temperature step
- max & min temperature

If someone has more option please comment this issue.

**Comment by flyman1664** [comment]
Hi,

If possible to add oscillation like swing ect.

Thanks for the good job

**Comment by joshepw** [comment]
@KiraPC the temperature step and max & min temperature is added, can you try it? I already tested.

**Comment by joshepw** [comment]
Released in stable version `1.0.0.`; added new option to select HVAC modes
