### ISSUE TITLE
Add binary sensor to entities to indicate device status

### ISSUE THREAD

**Issue by benswinburne** [KiraPC/ha-switchbot-remote#8]
I have an IR controlled air conditioner which I have attached an aqara contact sensor to. This sensor indicates whether or not the device is turned on. This would be useful for icons, status and possible power toggling of devices etc.

It'd be great if you are able to add support for binary sensors as status indicators for IR controlled devices

**Comment by KiraPC** [comment]
Hi @benswinburne yes, this feature is still in progress. If you have a TV remote you can add via customization entity in the integration option a power sensor.

I'll add soon also to other appliance.

**Comment by joshepw** [comment]
@benswinburne please can you test the `0.2.2-beta.2` version?

**Comment by joshepw** [comment]
Released in stable version `1.0.0.`
