### ISSUE TITLE
Please Add Support for Learned Devices

### ISSUE THREAD

**Issue by atxnyc** [KiraPC/ha-switchbot-remote#9]
I've been using this integration and its fantastic - one issue I've noticed though is that some AC settings are not supported by switchbot (silent mode, turbo mode, certain types of oscillation) and a workaround I have used is to create these using 'Learn Buttons' instead of smart matching or selecting a device manually. 

For example I have a setting for rapid cooling which maxes out the fan and chooses some settings not supported by switchbot, after learning the signal it is available as a basic On/Off switch which would be great for use in automations.

However, these types of remotes don't appear to be discovered by the integration currently - is it possible to add support for these? 

Some of the code, specifically the configure flow already appears to see these, but they don't show up as devices or entities

Custom Remote Type:
![image](https://github.com/KiraPC/ha-switchbot-remote/assets/57183688/4a7c0b06-ffa6-4669-aa66-f695c76117d5)

Appearance when Configured:
![image](https://github.com/KiraPC/ha-switchbot-remote/assets/57183688/4c97aa12-aeca-407a-970e-8659158b27a2)

Learned Remotes in Config Flow:
![image](https://github.com/KiraPC/ha-switchbot-remote/assets/57183688/4d7e2420-7b73-4963-a50a-81815eabce45)

But not present in devices:
![image](https://github.com/KiraPC/ha-switchbot-remote/assets/57183688/4cc481cc-141a-46e2-a037-978696085622)

**Comment by KiraPC** [comment]
Hello @atxnyc thanks for support.

Tra, i'll try to implements this asap.

**Comment by KiraPC** [comment]
@atxnyc unfortunately I guess this features will be delivered in September. I'm on vacation in my parent's town and I did not bring with me the switchbot hub that is necessary in order to get the response body with this learned device and integrate it in HA.

Otherwise you should send the api response (if you are able to get it by yourself) and paste it here and I'll try to analyze.

**Comment by atxnyc** [comment]
@KiraPC no worries at all -- I'll see if I can get the response out, but otherwise I'll look forward to September

**Comment by KiraPC** [comment]
@atxnyc I released the 0.2.1-beta.1 version. Could you please check if it is working?

**Comment by joshepw** [comment]
@atxnyc please can you test the `0.2.2-beta.2` version?
